---
date: "2020-04-26"
title: Introdução à Visualização de Dados
type: book
weight: 13
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
options(scipen=999)
```

## Principais gráficos

<br>

```{r}
data(iris)
library(ggplot2)
```

<br>

### Dispersão

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Petal.Length)) +
  geom_point()
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Petal.Length)) +
  geom_point(color = "blue", size = 3, alpha = 0.5) +
  labs(title = "Título do gráfico", x = "Eixo das abscissas", y = "Eixo das ordenadas")
```

<br>

### Histograma

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length)) +
  geom_histogram()
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length)) +
  geom_histogram(bins = 10, fill = "blue", color = "purple", alpha = 0.5) +
  labs(title = "Título do gráfico", x = "Eixo das abscissas", y = "Eixo das ordenadas")
```

<br>

### Boxplot

<br>

```{r}
ggplot(data = iris, mapping = aes(y = Sepal.Length)) +
  geom_boxplot()
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Species, y = Sepal.Length)) +
  geom_boxplot()
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Species, y = Sepal.Length)) +
  geom_boxplot(fill = "blue", color = "purple", alpha = 0.5) +
  labs(title = "Título do gráfico", x = "Eixo das abscissas", y = "Eixo das ordenadas")
```

<br>

### Barras e Colunas

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Species)) +
  geom_bar()
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Species)) +
  geom_bar(fill = "blue", alpha = 0.5)
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Species, y = Sepal.Length)) +
  geom_col(fill = "blue", alpha = 0.5)
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Species, y = Sepal.Length)) +
  geom_col(fill = "blue", alpha = 0.5) +
  labs(title = "Título do gráfico", x = "Eixo das abscissas", y = "Eixo das ordenadas")
```

<br>

### Linhas

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_line()
```

<br>

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_line(color = "blue") +
  geom_point(color = "purple") +
  labs(title = "Título do gráfico", x = "Eixo das abscissas", y = "Eixo das ordenadas")
```