---
title: Traduzindo instruções SQL para R utilizando o dplyr
author: acsjunior
date: '2019-05-26'
slug: []
categories:
  - Tutoriais
tags:
  - R
  - SQL
  - dplyr
  - tidyverse
  - data wrangling
subtitle: ''
summary: ''
authors: []
lastmod: '2019-05-26T14:48:37-03:00'
featured: no
image:
  caption: 'Crédito: [https://dplyr.tidyverse.org/](https://dplyr.tidyverse.org/)'
  focal_point: ''
  preview_only: no
projects: []
---

Quando comecei a programar em R a minha principal referência para manipulação de dados era a linguagem SQL. Por conta disso, diante de determinadas necessidades, eu desenvolvia a solução "pensando" em SQL e depois traduzia para R, mais ou menos como fazemos quando estamos aprendendo um novo idioma.

É claro que, com a prática, veio a fluência, entretanto, conhecer o pacote dplyr fez total diferença.

# O que é o dplyr?

De acordo com a definição da própria documentação, dplyr é uma gramática de manipulação de dados, que fornece um conjunto de verbetes que ajudam a resolver os desafios mais comuns de manipulação de dados.

## Mãos à obra

Neste post serão demonstradas algumas das principais funcionalidades deste poderoso pacote, fazendo um paralelo com a linguagem SQL para facilitar a absorção.

{{% callout note %}}
[Acesse a publicação completa no **Blog Ciência com Dados**](https://cienciacomdados.com.br/blog/2019-05-26-traduzindo-instru%C3%A7%C3%B5es-sql-para-r-utilizando-o-dplyr/).
{{% /callout %}}


