---
title: Como praticar SQL no Jupyter Notebook
author: acsjunior
date: '2023-07-15'
slug: []
categories:
  - Tutoriais
tags:
  - sql
  - python
subtitle: ''
summary: ''
authors: []
lastmod: '2023-07-15T20:00:00-00:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Um dos maiores desafios para pessoas sem vivência com linguagem de programação e que querem se tornar cientista de dados, é aprender Python ou R. E um dos maiores erros dessas pessoas é começarem por um curso de Python ou R para ciência de dados, sem saberem nada de bancos de dados e SQL. A maior parte do trabalho de ciência de dados realizado com estas ferramentas é por meio da manipulação de data frames (objetos que armazenam tabelas de dados), logo, saber lidar com dados tabulares torna-se essencial.

Embora não seja um requisito, ter uma boa base sobre bancos de dados relacionais e SQL pode tornar este aprendizado muito mais fluido e, por isso, não canso de recomendar: aprenda SQL! Contudo, sei que não é tão simples, para quem está começando, configurar um banco de dados para praticar. Portanto, o objetivo desse artigo é demonstrar como criar um simples banco de dados SQLite e executar instruções SQL por meio do Jupyter Notebook.

{{% callout note %}}
[Acesse a publicação completa no **Linkedin**](https://www.linkedin.com/pulse/como-praticar-sql-jupyter-notebook-ant%2525C3%2525B3nio-c-da-silva-j%2525C3%2525BAnior%3FtrackingId=3EBR16lwRkOGJmSA3Dg4vQ%253D%253D/?trackingId=3EBR16lwRkOGJmSA3Dg4vQ%3D%3D).
{{% /callout %}}
