---
title: Interface "drag and drop"​ para construção de gráficos no R
author: acsjunior
date: '2019-12-20'
slug: []
categories:
  - Tutoriais
tags:
  - r
  - ggplot2
  - esquisse
  - visualização de dados
subtitle: ''
summary: ''
authors: []
lastmod: '2019-12-20T15:16:14-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

A linguagem R possui excelentes recursos para uma boa análise descritiva, principalmente quando o assunto é visualização de dados. No entanto, a necessidade de digitar algumas linhas de código para conseguir plotar determinado gráfico pode complicar o trabalho de quem ainda não tem tanta fluência com a linguagem, pois convenhamos que interromper toda hora a nossa linha de raciocínio para pesquisar “como fazer” atrapalha um pouco.

O ggplot2 é um excelente pacote para visualização de dados, inclusive publiquei [este post](https://www.linkedin.com/pulse/visualizando-dados-em-r-com-ggplot2-antonio-c-da-silva-júnior/?lipi=urn%3Ali%3Apage%3Ad_flagship3_pulse_read%3B8vSShEP0Qr2eaZkzgmrp1A%3D%3D) sobre ele, porém é necessário um pouco de prática até adquirir fluência para redigir suas linhas de código e, consequentemente, plotar os visuais desejados, entretanto, o pacote **esquisse** pode tornar a nossa vida um pouco mais fácil.

De acordo com a documentação do pacote, o esquisse é um *add-in* que nos permite explorar interativamente os dados, visualizando-os com o pacote ggplot2. Em outras palavras, ao invés de digitar linhas de código, basicamente o que precisamos é arrastar a soltar as variavés e pronto, o gráfico está construído!

Vamos ver como esta mágica funciona.

{{% callout note %}}
[Acesse a publicação completa no **LinkedIn**](https://www.linkedin.com/pulse/interface-drag-drop-para-construção-de-gráficos-r-da-silva-júnior/).
{{% /callout %}}
